import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  CURATED_VIBE_PRESETS,
  generateVibeMix,
  type VibeBlueprint,
  type VibePreset
} from '../../services/vibeDj';
import { usePlayerStore } from '../../stores/playerStore';
import { useSettingsStore } from '../../stores/settingsStore';
import { useLibraryStore } from '../../stores/libraryStore';
import { unlockAudioEngine } from '../player/YouTubeEmbed';
import TrackRow from '../ui/TrackRow';
import GlassCard from '../ui/GlassCard';

export default function VibeDJPage() {
  const [prompt, setPrompt] = useState('');
  const [autoTuneStudio, setAutoTuneStudio] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeBlueprint, setActiveBlueprint] = useState<VibeBlueprint | null>(null);
  const [savedToast, setSavedToast] = useState(false);

  const playTrack = usePlayerStore((s) => s.playTrack);
  const setEqualizerPreset = useSettingsStore((s) => s.setEqualizerPreset);
  const setVisualizerStyle = useSettingsStore((s) => s.setVisualizerStyle);
  const setAccentColor = useSettingsStore((s) => s.setAccentColor);
  const createPlaylist = useLibraryStore((s) => s.createPlaylist);
  const addToPlaylist = useLibraryStore((s) => s.addToPlaylist);

  const launchVibe = async (input: string | VibePreset) => {
    // Synchronously unlock browser audio engine inside user gesture before async fetch
    unlockAudioEngine();
    setIsGenerating(true);
    setSavedToast(false);
    try {
      const blueprint = await generateVibeMix(input);
      setActiveBlueprint(blueprint);

      if (autoTuneStudio) {
        setEqualizerPreset(blueprint.eqPreset);
        setVisualizerStyle(blueprint.visualizerStyle);
        setAccentColor(blueprint.accentColor);
      }

      if (blueprint.tracks.length > 0) {
        playTrack(blueprint.tracks[0], blueprint.tracks, 0);
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim() || isGenerating) return;
    launchVibe(prompt.trim());
  };

  const handleSaveAsPlaylist = () => {
    if (!activeBlueprint || activeBlueprint.tracks.length === 0) return;
    const pl = createPlaylist(
      `✨ ${activeBlueprint.title}`,
      activeBlueprint.curatedDescription || `Generated by WaveCraft AI Vibe DJ — "${activeBlueprint.prompt}"`,
      activeBlueprint.tracks[0]?.thumbnail || ''
    );
    activeBlueprint.tracks.forEach((t) => addToPlaylist(pl.id, t));
    setSavedToast(true);
    setTimeout(() => setSavedToast(false), 3000);
  };

  return (
    <div className="p-6 sm:p-8 max-w-6xl mx-auto space-y-8 pb-28">
      {/* Hero Banner */}
      <div className="relative rounded-3xl overflow-hidden liquid-glass border border-white/15 p-7 sm:p-10 shadow-2xl">
        <div className="absolute -top-24 -right-24 w-96 h-96 rounded-full bg-[var(--color-accent)]/25 blur-[100px] pointer-events-none" />
        <div className="absolute -bottom-24 -left-24 w-96 h-96 rounded-full bg-purple-600/25 blur-[100px] pointer-events-none" />

        <div className="relative z-10 max-w-3xl">
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-white/10 border border-white/15 text-xs font-bold uppercase tracking-widest text-[var(--color-accent)] mb-4">
            <span className="w-2 h-2 rounded-full bg-[var(--color-accent)] animate-ping" />
            WaveCraft AI Vibe DJ
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight leading-tight">
            Describe your moment. <br />
            <span className="bg-gradient-to-r from-white via-rose-200 to-purple-300 bg-clip-text text-transparent">
              We’ll engineer the soundstage.
            </span>
          </h1>
          <p className="text-sm sm:text-base text-white/65 mt-3 max-w-2xl">
            Type any mood, activity, language, or artist fusion. WaveCraft automatically curates a continuous 320kbps flow and tunes your 10-Band EQ & 3D Visualizer to match.
          </p>

          {/* AI Vibe Prompt Bar */}
          <form onSubmit={handleFormSubmit} className="mt-6 space-y-3">
            <div className="flex flex-col sm:flex-row gap-3">
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder='e.g. "2AM coding in Tokyo rain", "Telugu mass gym PR", "90s AR Rahman nostalgia"...'
                className="flex-1 h-14 px-5 rounded-2xl bg-black/45 border border-white/20 text-white placeholder-white/40 text-sm sm:text-base focus:outline-none focus:border-[var(--color-accent)] transition-colors"
              />
              <button
                type="submit"
                disabled={isGenerating || !prompt.trim()}
                className="h-14 px-7 rounded-2xl glass-button-primary text-white font-extrabold text-sm sm:text-base cursor-pointer disabled:opacity-50 flex items-center justify-center gap-2.5 flex-shrink-0"
              >
                {isGenerating ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    <span>Mixing Vibe...</span>
                  </>
                ) : (
                  <>
                    <span>✨ Generate Mix</span>
                  </>
                )}
              </button>
            </div>

            <div className="flex items-center justify-between flex-wrap gap-2 pt-1">
              <label className="inline-flex items-center gap-2.5 text-xs text-white/70 cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={autoTuneStudio}
                  onChange={(e) => setAutoTuneStudio(e.target.checked)}
                  className="rounded accent-[var(--color-accent)] w-4 h-4"
                />
                <span>
                  Auto-tune <strong>10-Band Equalizer</strong>, <strong>3D Visualizer</strong> &{' '}
                  <strong>Ambient Glow</strong> to match vibe
                </span>
              </label>
            </div>
          </form>
        </div>
      </div>

      {/* 1-Tap Curated Vibe Orbs */}
      <section>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-bold text-white">Instant Vibe Spheres</h2>
          <span className="text-xs text-white/45">1-Click AI Soundstage Presets</span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {CURATED_VIBE_PRESETS.map((preset) => (
            <motion.button
              key={preset.id}
              whileHover={{ y: -3, scale: 1.01 }}
              whileTap={{ scale: 0.98 }}
              onClick={() => {
                setPrompt(preset.prompt);
                launchVibe(preset);
              }}
              className="text-left p-5 rounded-2xl liquid-glass border border-white/15 hover:border-white/30 transition-all group relative overflow-hidden cursor-pointer"
            >
              <div
                className={`absolute -right-8 -bottom-8 w-28 h-28 rounded-full bg-gradient-to-br ${preset.gradient} opacity-25 blur-2xl group-hover:opacity-50 transition-opacity`}
              />
              <div className="flex items-start justify-between gap-2">
                <span className="text-3xl">{preset.emoji}</span>
                <span className="px-2.5 py-1 rounded-full bg-white/10 text-[10px] font-bold text-white/75 uppercase tracking-wider whitespace-nowrap flex-shrink-0">
                  EQ: {preset.eqPreset}
                </span>
              </div>
              <h3 className="text-base font-extrabold text-white mt-3">{preset.title}</h3>
              <p className="text-xs text-white/55 mt-1 line-clamp-2">{preset.prompt}</p>
              <div className="mt-3 pt-2.5 border-t border-white/10 flex items-center justify-between gap-2 text-[11px] font-semibold text-white/65">
                <span className="whitespace-nowrap truncate">{preset.energyLabel}</span>
                <span className="text-[var(--color-accent)] group-hover:translate-x-1 transition-transform whitespace-nowrap flex-shrink-0">
                  Launch →
                </span>
              </div>
            </motion.button>
          ))}
        </div>
      </section>

      {/* Active Generated Vibe Blueprint & Tracklist */}
      {activeBlueprint && (
        <motion.section
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-4"
        >
          <GlassCard variant="liquid" padding="lg" className="border border-white/20">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-white/10">
              <div>
                <div className="flex flex-wrap items-center gap-2 mb-1.5">
                  <span className="px-2.5 py-0.5 rounded-full bg-[var(--color-accent)]/20 border border-[var(--color-accent)]/40 text-[11px] font-bold text-white">
                    {activeBlueprint.energyLabel}
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full bg-white/10 text-[11px] font-bold text-white/80">
                    EQ: {activeBlueprint.eqPreset}
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full bg-white/10 text-[11px] font-bold text-white/80">
                    3D: {activeBlueprint.visualizerStyle.toUpperCase()}
                  </span>
                </div>
                <h2 className="text-2xl font-extrabold text-white">{activeBlueprint.title}</h2>
                <p className="text-xs text-white/70 mt-0.5">{activeBlueprint.subtitle}</p>
                {activeBlueprint.curatedDescription && (
                  <p className="text-xs text-white/60 mt-2 leading-relaxed max-w-2xl bg-white/[0.04] p-2.5 rounded-xl border border-white/10">
                    💡 <span className="font-semibold text-white/90">DJ Set Notes:</span> {activeBlueprint.curatedDescription}
                  </p>
                )}
              </div>

              <div className="flex items-center gap-3">
                <button
                  onClick={() => {
                    if (activeBlueprint.tracks.length > 0) {
                      playTrack(activeBlueprint.tracks[0], activeBlueprint.tracks, 0);
                    }
                  }}
                  className="px-5 py-2.5 rounded-full glass-button-primary text-white font-extrabold text-xs cursor-pointer"
                >
                  ▶ Play Full Flow
                </button>
                <button
                  onClick={handleSaveAsPlaylist}
                  className="px-4 py-2.5 rounded-full glass-button text-white font-bold text-xs cursor-pointer"
                >
                  {savedToast ? '✓ Saved to Playlists!' : '+ Save as Playlist'}
                </button>
              </div>
            </div>

            <div className="mt-4 space-y-1">
              {activeBlueprint.tracks.map((track, idx) => (
                <TrackRow
                  key={track.id}
                  track={track}
                  index={idx + 1}
                  tracks={activeBlueprint.tracks}
                  onPlay={(t) => playTrack(t, activeBlueprint.tracks, idx)}
                />
              ))}
            </div>
          </GlassCard>
        </motion.section>
      )}
    </div>
  );
}
